### ISSUE TITLE
dataset文件夹下 缺乏了  utils这个脚本

### ISSUE THREAD

**Issue by chilljudaoren** [whdii/TMM#4]
dataset文件夹下 缺乏了  utils这个脚本，导致在运行EvalTransferAttack这个脚本时出现了如下报错（在caption_dataset脚本下：ModuleNotFoundError: No module named 'dataset.utils'）

**Comment by chilljudaoren** [comment]
已解决

**Comment by YanGGGL** [comment]
请问你是怎么解决的

**Comment by chilljudaoren** [comment]
你去看其他代码，它们有相同的脚本

YanGGGL ***@***.***> 于2024年10月8日周二 10:07写道：
